### ISSUE TITLE
feature: LinkML data models ?

### ISSUE THREAD

**Issue by markdoerr** [smart-data-models/dataModel.DCAT-AP#8]
Dear developers,

are you considering, using LinkML data models ?
[https://linkml.io/linkml/](https://linkml.io/linkml/)

They are very similar to your yaml models, and can then be converted to many other formats ....

**Comment by franckLG** [comment]
Hi,

That looks interesting and may help improving alignment of data models to NGSI-LD specification.

But a linkML to NGSI-LD converter would be needed.  

Any hints about the effort required to get such a converter, compliant with [NGSI-LD information model](https://www.etsi.org/deliver/etsi_gs/CIM/001_099/006/01.03.01_60/gs_CIM006v010301p.pdf) ?

**Comment by albertoabellagarcia** [comment]
Answering to [@markdoerr](https://github.com/markdoerr) we are glad to export in whatever format as long as there would be users and it can be done automatically. 

My experience in the service characteristics Gaia-x group with LinkML  is that it is quite early to use it as source of truth for all data models. 

Having said that, we would be glad to have such export and we could hold a call about it. Please book it here [https://calendly.com/smartdatamodels](https://calendly.com/smartdatamodels)
